sudo: false
dist: trusty
language: python
virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
    - python-fontforge

install:
  - pip install fonttools

script:
  - make normalize
  # Check no files were changed after normalization
  - git diff-index --quiet HEAD || (git diff && false)
  - make otf
