name: Fontship

on: [push, pull_request]

jobs:

  fontship:
    name: Fontship
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: |
          git fetch --prune --tags ||:
      - name: Fontship make
        id: fontship
        uses: theleagueof/fontship@latest
      - name: Upload artifacts
        uses: actions/upload-artifact@v2-preview
        with:
          name: ${{ steps.fontship.outputs.DISTDIR }}
          path: ${{ steps.fontship.outputs.DISTDIR }}.zip

  publish:
    name: Publish
    runs-on: ubuntu-20.04
    needs:
      - fontship
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ needs.fontship.outputs.DISTDIR }}.zip
            ${{ needs.fontship.outputs.DISTDIR }}.tar.xz
        env:
          GITHUB_TOKEN: ${{ github.token }}
